"""
Markdown report builder for the weekly CMMC compliance report.

The report is two-audience:
  1. Executive Summary (top) - a CISO or other senior leader reads this
     in 90 seconds. RAG status calculated deterministically in code,
     business-language narrative generated by the Foundry agent.
  2. Technical Appendix (bottom) - the security team digs into specific
     failing assessments here.

RAG status is computed from finding counts plus a "critical category"
keyword check so it doesn't depend on the AI's mood. Thresholds are
deliberately conservative and easy to tune for any org's risk appetite.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime
from typing import Any

# Topics that escalate severity regardless of count. Each is a category
# CMMC L2 specifically calls out as a baseline expectation; a single
# failing assessment in any of these warrants executive attention.
CRITICAL_KEYWORDS = [
    "encrypt at rest",
    "encryption at rest",
    "encrypt in transit",
    "public network",
    "anonymous access",
    "publicly accessible",
    "mfa",
    "multi-factor",
    "multifactor",
]


def calculate_rag_status(mapped_findings: list[dict[str, Any]]) -> tuple[str, str, str]:
    """
    Return (status_label, hex_color, headline).

    Thresholds:
      RED   - any critical-category failure with >=5 total failures,
              OR >20 total failures regardless of category
      AMBER - 5-20 failures
      GREEN - <5 failures
    """
    failing = [f for f in mapped_findings if f.get("State") == "Failed"]
    failing_count = len(failing)

    has_critical = any(
        any(kw in (f.get("Title") or "").lower() for kw in CRITICAL_KEYWORDS)
        for f in failing
    )

    if (has_critical and failing_count >= 5) or failing_count > 20:
        return ("RED", "#c0392b", "Significant gaps. Executive attention required this week.")
    if failing_count >= 5:
        return ("AMBER", "#d68910", "Manageable gaps. Targeted remediation needed.")
    return ("GREEN", "#1e8449", "Posture aligns with CMMC L2 expectations.")


def render_report(
    framework: str,
    standard: str,
    mapped_findings: list[dict[str, Any]],
    narrative: str,
    generated_at: datetime,
) -> tuple[str, str, str, str]:
    """
    Render the full Markdown report.

    Returns (report_md, rag_label, rag_color, rag_headline) so the email
    sender can prefix the subject with the status and color the banner.
    """
    rag_label, rag_color, rag_headline = calculate_rag_status(mapped_findings)

    total = len(mapped_findings)
    by_state = Counter(f.get("State") or "Unknown" for f in mapped_findings)
    failing_count = by_state.get("Failed", 0)
    passing_count = by_state.get("Passed", 0)

    by_domain: Counter = Counter()
    by_practice: Counter = Counter()
    for f in mapped_findings:
        for d in f.get("CMMCDomains", []):
            by_domain[d] += 1
        for p in f.get("CMMCPractices", []):
            by_practice[p] += 1

    lines = [
        # ======== EXECUTIVE SUMMARY ========
        f"# {framework} - Weekly Compliance Briefing",
        f"_{generated_at.strftime('%A, %B %d, %Y')}_  ",
        "",
        f"**Overall posture: {rag_label}**  ",
        f"{rag_headline}",
        "",
        f"_{passing_count} of {total} assessments currently passing. "
        f"{failing_count} failing._",
        "",
        "---",
        "",
        # Agent-generated business-language sections
        narrative,
        "",
        "---",
        "",
        # ======== TECHNICAL APPENDIX ========
        "# Technical Appendix",
        "_For the security team. Detailed findings backing the executive summary above._",
        "",
        "## Assessment Counts",
        f"- Total assessments analyzed: {total}",
        f"- Passing: {passing_count}",
        f"- Failing: {failing_count}",
        "",
        "## CMMC Domain Coverage",
        "_Number of findings touching each CMMC domain._",
        "",
    ]
    for domain, count in by_domain.most_common():
        lines.append(f"- `{domain}`: {count}")

    lines.extend(["", "## Top Practices by Finding Count", ""])
    for practice, count in by_practice.most_common(15):
        lines.append(f"- `{practice}`: {count}")

    lines.extend(["", "## Top Failing Assessments", ""])
    failing = [f for f in mapped_findings if f.get("State") == "Failed"]
    if not failing:
        lines.append("_No failing assessments in this run._")
    else:
        for f in failing[:25]:
            lines.append(
                f"- **{f.get('Title')}**  \n"
                f"  Defender control: `{f.get('ControlId')}`  \n"
                f"  Failed resources: {f.get('FailedResources') or 0}  \n"
                f"  CMMC practices: {', '.join(f.get('CMMCPractices') or [])}"
            )

    lines.extend([
        "",
        "---",
        "",
        "_Source: Microsoft Defender for Cloud regulatory compliance, "
        f"standard `{standard}`. Generated automatically by the "
        "azure-compliance-analyzer pipeline._",
    ])

    return ("\n".join(lines), rag_label, rag_color, rag_headline)
